import { NextRequest, NextResponse } from "next/server";
import OpenAI, { toFile } from "openai";
import fs from "fs/promises";
import path from "path";
import crypto from "crypto";
import { deliver } from "@/lib/delivery";
import { addFooterStrip } from "@/lib/branding";

export const runtime = "nodejs";
export const maxDuration = 300; // image generation can take a couple of minutes

function buildPrompt(attributes: string[]): string {
  const attrText = attributes.length > 0 ? attributes.join(", ") : "";
  const attrSentence = attrText
    ? `Add items to reflect that they're known for ${attrText}. `
    : "";
  return (
    "Transform this photo into a cute Pixar/Disney-style baby caricature of this specific person — " +
    "the result should be instantly recognizable as them, not a generic baby. " +
    "Faithfully preserve: their exact hairstyle (length, cut, curl or straightness, parting) and hair color " +
    "including any highlights; their eye color and eye shape — enlarge the eyes only moderately and keep " +
    "their real shape rather than defaulting to big round eyes; eyebrow shape; skin tone; face shape; " +
    "their smile and expression; and glasses, facial hair, freckles, moles, or dimples if present. " +
    "Keep distinctive accessories such as earrings, necklaces, headbands, or hair clips, and dress the baby " +
    "in a baby-sized version of their actual outfit. " +
    "Render them as an adorable cartoon infant with soft chubby cheeks and an oversized head-to-body ratio, " +
    "warm pastel color palette. " +
    attrSentence +
    "Clean simple background, soft studio lighting, high-quality illustration style, no text."
  );
}

export async function POST(req: NextRequest) {
  // Every request gets a short id so its log lines can be found in the
  // Vercel dashboard (Project → Logs) and correlated with client errors.
  const reqId = crypto.randomBytes(3).toString("hex");
  const started = Date.now();
  const elapsed = () => `${((Date.now() - started) / 1000).toFixed(1)}s`;
  const log = (message: string) => console.log(`[generate ${reqId}] ${message} (t+${elapsed()})`);
  const fail = (status: number, error: string, cause?: unknown) => {
    console.error(`[generate ${reqId}] FAILED (HTTP ${status}) at t+${elapsed()}: ${error}`, cause ?? "");
    return NextResponse.json({ ok: false, error, requestId: reqId }, { status });
  };

  let body: { name?: string; email?: string; attributes?: string[]; imageDataUrl?: string };
  try {
    body = await req.json();
  } catch (err) {
    return fail(400, "Could not read the upload (request body was not valid JSON — the connection may have been cut off mid-upload)", err);
  }

  const name = (body.name || "").trim();
  const email = (body.email || "").trim();
  const attributes = (body.attributes || []).map((a) => a.trim()).filter(Boolean);
  const imageDataUrl = body.imageDataUrl || "";

  if (!name || !email || !imageDataUrl.startsWith("data:image/")) {
    return fail(400, `Missing name, email, or photo (name=${!!name}, email=${!!email}, photo=${imageDataUrl.slice(0, 20)}...)`);
  }
  const apiKey = process.env.OPENAI_API_KEY || process.env.CHATGPT_API_KEY;
  if (!apiKey) {
    return fail(500, "OPENAI_API_KEY is not set on the server (check Vercel → Settings → Environment Variables)");
  }

  const mime = imageDataUrl.match(/^data:(image\/[a-z+]+);base64,/)?.[1] ?? "image/png";
  const photoBuffer = Buffer.from(imageDataUrl.slice(imageDataUrl.indexOf(",") + 1), "base64");
  log(
    `request from "${name}" <${email}> — photo ${mime} ${(photoBuffer.length / 1024).toFixed(0)}KB, ` +
      `attributes: [${attributes.join(", ")}]`
  );

  const model = process.env.IMAGE_MODEL || "gpt-image-2";
  const quality = (process.env.IMAGE_QUALITY as "low" | "medium" | "high") || "high";

  let generated: Buffer;
  try {
    const openai = new OpenAI({ apiKey });
    const params: Record<string, unknown> = {
      model,
      image: await toFile(photoBuffer, mime === "image/jpeg" ? "photo.jpg" : "photo.png", { type: mime }),
      prompt: buildPrompt(attributes),
      size: "1024x1024",
      quality,
    };
    // gpt-image-1 / 1.5 need this to preserve the person's face well;
    // gpt-image-2 always uses high input fidelity and rejects the param.
    if (model.startsWith("gpt-image-1")) params.input_fidelity = "high";
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await openai.images.edit(params as any);
    const b64 = result.data?.[0]?.b64_json;
    if (!b64) throw new Error("OpenAI returned no image data");
    generated = Buffer.from(b64, "base64");
    log(`image generated by ${model} (quality=${quality}), ${(generated.length / 1024).toFixed(0)}KB`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return fail(502, `Image generation failed (${model}, quality=${quality}): ${message}`, err);
  }

  // Add the white footer strip with the event name. If that ever fails, the
  // unbranded image still goes out — better than no image at all.
  try {
    generated = await addFooterStrip(generated);
    log(`footer strip added, final image ${(generated.length / 1024).toFixed(0)}KB`);
  } catch (err) {
    console.error(`[generate ${reqId}] footer strip failed, sending unbranded image:`, err);
  }

  // Keep a local copy when running on a real machine. On Vercel the
  // filesystem is read-only, so the organizer email is the backup there.
  if (process.env.VERCEL) {
    log("skipping local copy (Vercel filesystem is read-only)");
  } else {
    try {
      const dir = path.join(process.cwd(), "generated");
      await fs.mkdir(dir, { recursive: true });
      const safeName = name.replace(/[^a-z0-9 _-]/gi, "").trim().replace(/\s+/g, "-").toLowerCase();
      await fs.writeFile(path.join(dir, `${safeName}-${Date.now()}.png`), generated);
    } catch (err) {
      console.error(`[generate ${reqId}] could not save local copy:`, err);
    }
  }

  const problems = await deliver({ guestName: name, email, image: generated });
  for (const p of problems) console.error(`[generate ${reqId}] delivery issue for ${name}: ${p}`);
  log(problems.length ? `done, but with ${problems.length} delivery issue(s)` : "done — emails sent");

  return NextResponse.json({ ok: true, problems, requestId: reqId });
}
